"""LABCLIP: Linear Attribute Binding for CLIP text embeddings.

CLIP's cross-modal alignment exhibits bag-of-words (BoW) behavior — it loses
attribute-object binding (can't distinguish "red shirt with blue pants" from
"blue shirt with red pants"). LABCLIP applies a learned linear transformation
to text embeddings to recover this binding information.

The linear transform is trained on synthetic hard negatives generated by
permuting attribute-object pairs in captions. No encoder retraining needed.

Reference: kdariina/CLIP-not-BoW-unimodally (ICLR 2026)
"""

import numpy as np
import torch
import torch.nn as nn
from typing import List, Tuple, Optional
from pathlib import Path
import json


class LABCLIPTransform(nn.Module):
    """Linear transformation layer for CLIP text embeddings.

    Applies W @ x where W is a learned (dim x dim) matrix.
    Initialized as identity (no change) and trained on hard negatives.
    """

    def __init__(self, dim: int = 512):
        super().__init__()
        self.dim = dim
        self.linear = nn.Linear(dim, dim, bias=False)
        # Initialize as identity
        with torch.no_grad():
            self.linear.weight.copy_(torch.eye(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear(x)

    def transform_numpy(self, x: np.ndarray) -> np.ndarray:
        """Apply transform to a numpy embedding."""
        with torch.no_grad():
            x_torch = torch.from_numpy(x.astype(np.float32))
            transformed = self.forward(x_torch)
            return transformed.numpy()

    def save(self, path: str) -> None:
        """Save the linear transform weights."""
        weights = self.linear.weight.detach().cpu().numpy()
        np.save(path, weights)

    def load(self, path: str) -> None:
        """Load the linear transform weights."""
        weights = np.load(path)
        with torch.no_grad():
            self.linear.weight.copy_(torch.from_numpy(weights.astype(np.float32)))


def generate_hard_negatives(
    captions: List[str],
    color_item_pairs: List[Tuple[str, str]],
    num_negatives: int = 1,
) -> List[Tuple[str, str]]:
    """Generate hard negatives by permuting attribute-object pairs.

    Example:
        Original: "red shirt with blue pants"
        Negative: "blue shirt with red pants" (swapped colors)

    Args:
        captions: List of original captions.
        color_item_pairs: List of (color, item) pairs found in captions.
        num_negatives: Number of negatives per original.

    Returns:
        List of (positive_caption, negative_caption) pairs.
    """
    pairs = []

    for caption in captions:
        # Find all color-item pairs in the caption
        found_pairs = []
        for color, item in color_item_pairs:
            if color in caption.lower() and item in caption.lower():
                found_pairs.append((color, item))

        if len(found_pairs) < 2:
            continue

        # Generate negatives by swapping colors between items
        for i in range(min(num_negatives, len(found_pairs) - 1)):
            neg_caption = caption.lower()
            c1, g1 = found_pairs[0]
            c2, g2 = found_pairs[1]

            # Swap colors
            neg_caption = neg_caption.replace(f"{c1} {g1}", "TEMP1_TEMP")
            neg_caption = neg_caption.replace(f"{c2} {g2}", f"{c1} {g2}")
            neg_caption = neg_caption.replace("TEMP1_TEMP", f"{c2} {g1}")

            pairs.append((caption, neg_caption))

    return pairs


def train_labclip(
    model_wrapper,
    captions: List[str],
    color_item_pairs: List[Tuple[str, str]],
    num_epochs: int = 100,
    lr: float = 1e-4,
    margin: float = 0.1,
    device: str = "cuda" if torch.cuda.is_available() else "cpu",
) -> LABCLIPTransform:
    """Train LABCLIP linear transform on hard negatives.

    Uses margin ranking loss: positive pair similarity should be higher
    than negative pair similarity by at least `margin`.

    Args:
        model_wrapper: CLIP wrapper with encode_text method.
        captions: List of captions to generate hard negatives from.
        color_item_pairs: Attribute-object pairs for generating negatives.
        num_epochs: Training epochs.
        lr: Learning rate.
        margin: Margin for ranking loss.
        device: Training device.

    Returns:
        Trained LABCLIPTransform.
    """
    dim = model_wrapper.embedding_dim
    transform = LABCLIPTransform(dim).to(device)

    # Generate hard negatives
    hard_neg_pairs = generate_hard_negatives(captions, color_item_pairs, num_negatives=3)

    if not hard_neg_pairs:
        print("No hard negatives generated. Returning identity transform.")
        return transform

    print(f"Generated {len(hard_neg_pairs)} hard negative pairs.")

    # Encode all captions with base CLIP (frozen)
    with torch.no_grad():
        pos_texts = [p[0] for p in hard_neg_pairs]
        neg_texts = [p[1] for p in hard_neg_pairs]

        pos_embeddings = torch.from_numpy(model_wrapper.encode_text(pos_texts)).to(device)
        neg_embeddings = torch.from_numpy(model_wrapper.encode_text(neg_texts)).to(device)

    # Also encode corresponding image embeddings if available
    # For now, use text-only training (uni-modal alignment)

    optimizer = torch.optim.Adam(transform.parameters(), lr=lr)
    loss_fn = nn.MarginRankingLoss(margin=margin)

    transform.train()
    for epoch in range(num_epochs):
        optimizer.zero_grad()

        # Transform text embeddings
        transformed_pos = transform(pos_embeddings)
        transformed_neg = transform(neg_embeddings)

        # Use a reference embedding (mean of positives) as anchor
        # Goal: positive should be closer to anchor than negative
        anchor = transformed_pos.mean(dim=0, keepdim=True).expand_as(transformed_pos)

        pos_sim = torch.cosine_similarity(transformed_pos, anchor, dim=-1)
        neg_sim = torch.cosine_similarity(transformed_neg, anchor, dim=-1)

        # Margin ranking loss: pos_sim should be > neg_sim + margin
        target = torch.ones_like(pos_sim)
        loss = loss_fn(pos_sim, neg_sim, target)

        loss.backward()
        optimizer.step()

        if (epoch + 1) % 20 == 0:
            print(f"  Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")

    transform.eval()
    return transform
